LesGrupo8Bioterio/Models/Ensaio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace LesGrupo8Bioterio
{
    public partial class Ensaio
    {
        public int IdEnsaio { get; set; }
        [Required(ErrorMessage = "É necessário preecnher este campo para Prosseguir")]
        [Display(Name = "Data de Inicio")]
        public DateTime DataInicio { get; set; }
        [Required(ErrorMessage = "É necessário preecnher este campo para Prosseguir")]
        [Display(Name = "Data de Fim")]
        public DateTime DataFim { get; set; }
        [Required(ErrorMessage = "É necessário preecnher este campo para Prosseguir")]
        [Display(Name = "Descrição de Tratamento")]
        public string DescTratamento { get; set; }
        [Required(ErrorMessage = "É necessário preecnher este campo para Prosseguir")]
        [Display(Name = "Grau de Severidade")]
        public int GrauSeveridade { get; set; }
        [Required(ErrorMessage = "É necessário preecnher este campo para Prosseguir")]
        [Display(Name = "Nº de Animais Autorizados")]
        public int? NroAnimaisAutoriz { get; set; }
        [Display(Name = "Projeto")]
        public int ProjetoIdProjeto { get; set; }
        public int LoteIdLote { get; set; }
        public Lote LoteIdLoteNavigation { get; set; }
        public Projeto ProjetoIdProjetoNavigation { get; set; }
        public Projeto Selected;
        public string data;
        public string data2;
        public IQueryable<Projeto> objetoP;
        public int isarchived { get; set; }
    }
}

LesGrupo8Bioterio/Controllers/EnsaiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LesGrupo8Bioterio;
using LesGrupo8Bioterio.Models;

namespace LesGrupo8Bioterio.Controllers
{
    public class EnsaiosController : Controller
    {
        private readonly bd_lesContext _context;

        public EnsaiosController(bd_lesContext context)
        {
            _context = context;
        }

        // GET: Ensaios
        public async Task<IActionResult> Index()
        {
            var bd_lesContext = _context.Ensaio.Include(e => e.LoteIdLoteNavigation).Include(e => e.ProjetoIdProjetoNavigation);
            return View(await bd_lesContext.ToListAsync());
        }

        // GET: Ensaios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ensaio = await _context.Ensaio
                .Include(e => e.LoteIdLoteNavigation)
                .Include(e => e.ProjetoIdProjetoNavigation)
                .SingleOrDefaultAsync(m => m.IdEnsaio == id);
            if (ensaio == null )
            {
                return NotFound();
            }

            ensaio.data = ensaio.DataInicio.Day + "/" + ensaio.DataInicio.Month + "/" + ensaio.DataInicio.Year;
            ensaio.data2 = ensaio.DataFim.Day + "/" + ensaio.DataFim.Month + "/" + ensaio.DataFim.Year;
            return View(ensaio);
        }

        // GET: Ensaios/Create
        public IActionResult Create()
        {
           
                ViewData["LoteIdLote"] = new SelectList(_context.Lote, "IdLote", "CodigoLote");
                ViewData["ProjetoIdProjeto"] = new SelectList( _context.Projeto.Where( p => p.isarchived == 0), "IdProjeto", "Nome");
            
            return View();
        }

        // POST: Ensaios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdEnsaio,DataInicio,DataFim,DescTratamento,GrauSeveridade,NroAnimaisAutoriz,ProjetoIdProjeto,LoteIdLote")] Ensaio ensaio)
        {

            if (ensaio.DataFim < ensaio.DataInicio)
            {
                ModelState.AddModelError("DataFim", "A Data de Fim é menor que a Data de Inicio");
                ModelState.AddModelError("DataInicio", "A Data de Fim é menor que a Data de Inicio");
            }
            var projetos = _context.Projeto.Where(b => EF.Property<int>(b, "IdProjeto") == ensaio.ProjetoIdProjeto);
            foreach (var projeto in projetos) { 
                if (ensaio.NroAnimaisAutoriz > projeto.NroAnimaisAutoriz)
                {
                    ModelState.AddModelError("NroAnimaisAutoriz", "Nº de Animais excede o permitido para o Projeto selecionado" + "(" + projeto.NroAnimaisAutoriz + ")");
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(ensaio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoteIdLote"] = new SelectList(_context.Lote, "IdLote", "CodigoLote", ensaio.LoteIdLote);
            ViewData["ProjetoIdProjeto"] = new SelectList(_context.Projeto, "IdProjeto", "Nome", ensaio.ProjetoIdProjeto);
            return View(ensaio);
        }

        // GET: Ensaios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ensaio = await _context.Ensaio.SingleOrDefaultAsync(m => m.IdEnsaio == id);
            if (ensaio == null || ensaio.isarchived == 1)
            {
                return NotFound();
            }
            ViewData["LoteIdLote"] = new SelectList(_context.Lote, "IdLote", "CodigoLote", ensaio.LoteIdLote);
            ViewData["ProjetoIdProjeto"] = new SelectList(_context.Projeto, "IdProjeto", "Nome", ensaio.ProjetoIdProjeto);
            return View(ensaio);
        }

        // POST: Ensaios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdEnsaio,DataInicio,DataFim,DescTratamento,GrauSeveridade,NroAnimaisAutoriz,ProjetoIdProjeto,LoteIdLote")] Ensaio ensaio)
        {
            if (id != ensaio.IdEnsaio)
            {
                return NotFound();
            }

            if (ensaio.DataFim < ensaio.DataInicio)
            {
                ModelState.AddModelError("DataFim", "A Data de Fim é menor que a Data de Inicio");
                ModelState.AddModelError("DataInicio", "A Data de Fim é menor que a Data de Inicio");
            }
            var projetos = _context.Projeto.Where(b => EF.Property<int>(b, "IdProjeto") == ensaio.ProjetoIdProjeto);
            foreach (var projeto in projetos)
            {
                if (ensaio.NroAnimaisAutoriz > projeto.NroAnimaisAutoriz)
                {
                    ModelState.AddModelError("NroAnimaisAutoriz", "Nº de Animais excede o permitido para o Projeto selecionado" + "(" + projeto.NroAnimaisAutoriz + ")");
                }
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ensaio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnsaioExists(ensaio.IdEnsaio))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoteIdLote"] = new SelectList(_context.Lote, "IdLote", "CodigoLote", ensaio.LoteIdLote);
            ViewData["ProjetoIdProjeto"] = new SelectList(_context.Projeto, "IdProjeto", "Nome", ensaio.ProjetoIdProjeto);
            return View(ensaio);
        }

        // GET: Ensaios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var ensaio = await _context.Ensaio
                .Include(e => e.LoteIdLoteNavigation)
                .Include(e => e.ProjetoIdProjetoNavigation)
                .SingleOrDefaultAsync(m => m.IdEnsaio == id);
            if (ensaio == null || ensaio.isarchived == 1)
            {
                return NotFound();
            }

            ensaio.data = ensaio.DataInicio.Day + "/" + ensaio.DataInicio.Month + "/" + ensaio.DataInicio.Year;
            ensaio.data2 = ensaio.DataFim.Day + "/" + ensaio.DataFim.Month + "/" + ensaio.DataFim.Year;
            return View(ensaio);
        }

        // POST: Ensaios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ensaio = await _context.Ensaio.SingleOrDefaultAsync(m => m.IdEnsaio == id);
            _context.Ensaio.Remove(ensaio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnsaioExists(int id)
        {
            return _context.Ensaio.Any(e => e.IdEnsaio == id);
        }
    }
}

LesGrupo8Bioterio/Views/Ensaios/Create.cshtml
@model LesGrupo8Bioterio.Ensaio
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="breadcrumb-item"><a asp-controller="Ensaios" asp-action="Index">Ensaios</a></li>
        <li class="breadcrumb-item active" aria-current="page">Criar</li>
    </ol>
</nav>
<h2>Criar</h2>
<h4>Ensaio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Projeto" data-content="Projeto onde o Ensaio irá ser realziado"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="ProjetoIdProjeto" class="control-label"></label>
                <select asp-for="ProjetoIdProjeto" class="form-control" asp-items="ViewBag.ProjetoIdProjeto"></select>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Lote" data-content="Lote que contêm os espécimes que irão fazer parte do ensaio"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="LoteIdLote" class="control-label"></label>
                <select asp-for="LoteIdLote" class="form-control" asp-items="ViewBag.LoteIdLote"></select>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Animais autorizados" data-content="Número de animais autorizados para o Ensaio"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="NroAnimaisAutoriz" class="control-label"></label>
                <input asp-for="NroAnimaisAutoriz" class="form-control" required />
                <span asp-validation-for="NroAnimaisAutoriz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Data de Inicio" data-content="Data na qual se pretende iniciar o Ensaio"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="DataInicio" class="control-label"></label>
                <input type="date" asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Data Final" data-content="Data na qual se preve o término do Ensaio"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="DataFim" class="control-label"></label>
                <input type="date" asp-for="DataFim" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Descrição do Tratamento" data-content="Tratamento que irá ser realizados sobre os espécimes durante o Ensaio"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="DescTratamento" class="control-label"></label>
                <input asp-for="DescTratamento" class="form-control" />
                <span asp-validation-for="DescTratamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Grau de Severidade" data-content="Grau de Severidade do Tratamento realizado"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="GrauSeveridade" class="control-label"></label>
                <input asp-for="GrauSeveridade" class="form-control" />
                <span asp-validation-for="GrauSeveridade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Confirmar" class="btn btn-success" />
                <a class="btn btn-info" asp-action="Index">Cancelar</a>
            </div>
        </form>
    </div>
</div>

<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
    });</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LesGrupo8Bioterio/Views/Ensaios/Delete.cshtml
@model LesGrupo8Bioterio.Ensaio

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="breadcrumb-item"><a asp-controller="Ensaios" asp-action="Index">Ensaios</a></li>
        <li class="breadcrumb-item active" aria-current="page">Apagar</li>
    </ol>
</nav>
<h2>Eliminar</h2>

<h3 class="alert alert-danger">
    <ul>
        <li> Tem a certeza que pretende Eliminar este Ensaio?</li>
        <li>Ao Eliminar este Ensaio estará a Eliminar todos as  evidências do ensaio ter ocorrido!</li>
       
    </ul>
</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DescTratamento)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DescTratamento)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GrauSeveridade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GrauSeveridade)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.LoteIdLoteNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LoteIdLoteNavigation.CodigoLote)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProjetoIdProjetoNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProjetoIdProjetoNavigation.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdEnsaio" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> 
        <a type="button" class="btn btn-primary" asp-action="Index">Cancelar</a>
    </form>
</div>

LesGrupo8Bioterio/Views/Ensaios/Details.cshtml
@model LesGrupo8Bioterio.Ensaio
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="breadcrumb-item"><a asp-controller="Ensaios" asp-action="Index">Ensaios</a></li>
        <li class="breadcrumb-item active" aria-current="page">Detalhes</li>
    </ol>
</nav>
@if (Model.isarchived == 1)
{
    <h3 class="alert alert-danger">
        <ul>
            <li> Este Ensaio encontra-se <b>Arquivado</b> </li>
        </ul>
    </h3>
}
<div>
    <h4>Ensaio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data2)
        </dd>
        <dt>
            @*@Html.DisplayNameFor(model => model.DescTratamento)*@Descrição do Ensaio
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DescTratamento)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GrauSeveridade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GrauSeveridade)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.LoteIdLoteNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LoteIdLoteNavigation.CodigoLote)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProjetoIdProjetoNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProjetoIdProjetoNavigation.Nome)
        </dd>
    </dl>
</div>
<div>
    @if (Model.isarchived == 0)
    {
        <a type="button" class="btn btn-success" asp-action="Edit" asp-route-id="@Model.IdEnsaio">Editar</a>}
    <a type="button" class="btn btn-primary" asp-action="Index">Retornar</a>
    @if (Model.isarchived == 0)
    {
        <a type="button" class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.IdEnsaio">Apagar Ensaio</a>}
    </div>

LesGrupo8Bioterio/Views/Ensaios/Edit.cshtml
@model LesGrupo8Bioterio.Ensaio
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="breadcrumb-item"><a asp-controller="Ensaios" asp-action="Index">Ensaios</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar</li>
    </ol>
</nav>
<h2>Editar</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdEnsaio" />
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Projeto" data-content="Projeto onde o Ensaio irá ser realziado"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="ProjetoIdProjeto" class="control-label"></label>
                <select asp-for="ProjetoIdProjeto" class="form-control" asp-items="ViewBag.ProjetoIdProjeto"></select>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Lote" data-content="Lote que contêm os espécimes que irão fazer parte do ensaio"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="LoteIdLote" class="control-label"></label>
                <select asp-for="LoteIdLote" class="form-control" asp-items="ViewBag.LoteIdLote"></select>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Animais autorizados" data-content="Número de animais autorizados para o Ensaio"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="NroAnimaisAutoriz" class="control-label"></label>
                <input asp-for="NroAnimaisAutoriz" class="form-control" required />
                <span asp-validation-for="NroAnimaisAutoriz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Data de Inicio" data-content="Data na qual se pretende iniciar o Ensaio"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="DataInicio" class="control-label"></label>
                <input type="date" asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Data Final" data-content="Data na qual se prevê o término do Ensaio"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="DataFim" class="control-label"></label>
                <input type="date" asp-for="DataFim" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Descrição do Tratamento" data-content="Tratamento que irá ser realizado sobre os espécimes durante o Ensaio"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="DescTratamento" class="control-label"></label>
                <input asp-for="DescTratamento" class="form-control" />
                <span asp-validation-for="DescTratamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Grau de Severidade" data-content="Grau de Severidade do Tratamento realizado"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="GrauSeveridade" class="control-label"></label>
                <input asp-for="GrauSeveridade" class="form-control" />
                <span asp-validation-for="GrauSeveridade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<div>
    <a type="button" class="btn btn-primary" asp-action="Index">Retornar</a>
</div>
<script>
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover();
    });
</script>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LesGrupo8Bioterio/Views/Ensaios/Index.cshtml
@model IEnumerable<LesGrupo8Bioterio.Ensaio>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="breadcrumb-item active" aria-current="page">Ensaios</li>
    </ol>
</nav>
<h2>Ensaios</h2>
<div class="form-group">
    <a class="btn btn-info" asp-action="Create">Criar Ensaio</a>
</div>
<div class="col-md-9">
    <ul class="nav nav-tabs" style="text-align: left;">
        <li class="active"><a href="#ensaios" data-toggle="tab" id="first_tab"><b>Ensaios Ativos</b></a></li>

    </ul>
</div>
<div class="col-md-9">
    <div class="tab-content">
        <div id="ensaios" class="tab-pane fade in active">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @*@Html.DisplayNameFor(model => model.ProjetoIdProjetoNavigation)*@Projeto
                        </th>
                        <th>
                            @*@Html.DisplayNameFor(model => model.LoteIdLoteNavigation)*@Lote
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.NroAnimaisAutoriz)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DataInicio)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DataFim)
                        </th>
                        <th>
                            @*@Html.DisplayNameFor(model => model.DescTratamento)*@Descrição do Ensaio
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.GrauSeveridade)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        if (item.isarchived == 0)
                        {
                            item.data = item.DataInicio.Day + "/" + item.DataInicio.Month + "/" + item.DataInicio.Year;
                            item.data2 = item.DataFim.Day + "/" + item.DataFim.Month + "/" + item.DataFim.Year;

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProjetoIdProjetoNavigation.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LoteIdLoteNavigation.CodigoLote)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NroAnimaisAutoriz)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.data)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.data2)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DescTratamento)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GrauSeveridade)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.IdEnsaio"><span class="glyphicon glyphicon-pencil"></span></a>
                            <a asp-action="Details" asp-route-id="@item.IdEnsaio"><span class="glyphicon glyphicon-eye-open"></span></a>
                            <a asp-action="Delete" asp-route-id="@item.IdEnsaio"><span class="glyphicon glyphicon-trash"></span></a>
                        </td>
                    </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
 
</div>
<div class="col-md-3 col-md-push-1">
    <ul class="list-group">
        <li class="list-group-item active"><b>Opções</b></li>
        <li class="list-group-item"><a asp-area="" asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="list-group-item"><a asp-area="" asp-controller="Elementoequipas" asp-action="Index">Equipas</a></li>

    </ul>
</div>