LesGrupo8Bioterio/Controllers/MotivoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LesGrupo8Bioterio;
using LesGrupo8Bioterio.Models;

namespace LesGrupo8Bioterio.Controllers
{
    public class MotivoesController : Controller
    {
        private readonly bd_lesContext _context;

        public MotivoesController(bd_lesContext context)
        {
            _context = context;
        }
        private Motivo setRelations(Motivo motivo, int? id)
        {



            var regRemocoes = _context.RegRemocoes.Where(b => EF.Property<int>(b, "MotivoIdMotivo") == id);
            motivo.regRemocoes = regRemocoes;

            if (motivo.regRemocoes.Any())
            {
                motivo.isDeletable = false;
            }
            else
            {
                motivo.isDeletable = true;
            }
            return motivo;
        }
        // GET: Motivoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Motivo.ToListAsync());
        }

        // GET: Motivoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var motivo = await _context.Motivo
                .SingleOrDefaultAsync(m => m.IdMotivo == id);
            if (motivo == null)
            {
                return NotFound();
            }

            return View(motivo);
        }

        // GET: Motivoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Motivoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdMotivo,TipoMotivo,NomeMotivo")] Motivo motivo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(motivo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(motivo);
        }

        // GET: Motivoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var motivo = await _context.Motivo.SingleOrDefaultAsync(m => m.IdMotivo == id);
            if (motivo == null)
            {
                return NotFound();
            }
            return View(motivo);
        }

        // POST: Motivoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdMotivo,TipoMotivo,NomeMotivo")] Motivo motivo)
        {
            if (id != motivo.IdMotivo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(motivo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MotivoExists(motivo.IdMotivo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(motivo);
        }

        // GET: Motivoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }
            
            var motivo = await _context.Motivo
                .SingleOrDefaultAsync(m => m.IdMotivo == id);
            motivo = setRelations(motivo, motivo.IdMotivo);
            if (motivo == null)
            {
                return NotFound();
            }

            return View(motivo);
        }

        // POST: Motivoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var motivo = await _context.Motivo.SingleOrDefaultAsync(m => m.IdMotivo == id);
         
                _context.Motivo.Remove(motivo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            }

        private bool MotivoExists(int id)
        {
            return _context.Motivo.Any(e => e.IdMotivo == id);
        }
    }
}

LesGrupo8Bioterio/Views/Motivoes/Create.cshtml
@model LesGrupo8Bioterio.Motivo
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="breadcrumb-item"><a asp-controller="CircuitoTanques" asp-action="Index">Circuito de Tanques</a></li>
        <li class="breadcrumb-item"><a asp-controller="Tanques" asp-action="Index">Tanques</a></li>
        <li class="breadcrumb-item"><a asp-controller="RegRemocoes" asp-action="Index">Registo de Remoções</a></li>
        <li class="breadcrumb-item"><a asp-controller="Motivoes" asp-action="Index">Motivos de Remoção</a></li>
        <li class="breadcrumb-item active" aria-current="page">Criar</li>
    </ol>
</nav>

<h2>Criar</h2>
<h4>Motivo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Tipo de Motivo" data-content="Tipo de Motivo de Remoção de Individuos"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="TipoMotivo" class="control-label"></label>
                <input asp-for="TipoMotivo" class="form-control" />
                <span asp-validation-for="TipoMotivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Designação do Motivo" data-content="Designação do Motivo que leva à remoção de Individuos"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="NomeMotivo" class="control-label"></label>
                <input asp-for="NomeMotivo" class="form-control" />
                <span asp-validation-for="NomeMotivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-success" />
                <a type="button" class="btn btn-info" asp-action="Index">Cancelar</a>
            </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover();
    });</script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LesGrupo8Bioterio/Views/Motivoes/Delete.cshtml
@model LesGrupo8Bioterio.Motivo
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="breadcrumb-item"><a asp-controller="CircuitoTanques" asp-action="Index">Circuito de Tanques</a></li>
        <li class="breadcrumb-item"><a asp-controller="Tanques" asp-action="Index">Tanques</a></li>
        <li class="breadcrumb-item"><a asp-controller="RegRemocoes" asp-action="Index">Registo de Remoções</a></li>
        <li class="breadcrumb-item"><a asp-controller="Motivoes" asp-action="Index">Motivos de Remoção</a></li>
        <li class="breadcrumb-item active" aria-current="page">Eliminar</li>
    </ol>
</nav>

<h3 class="alert alert-danger">
    @if (Model.isDeletable) { 
        <ul>
            <li> Tem a certeza que pretende Eliminar este motivo?</li>
        </ul>
    <ul>
        <li id="kk" hidden="hidden">Impossivel eliminar este Motivo</li>
    </ul>
    }
    @if (!Model.isDeletable) { 
        <ul>
            <li> Este Motivo não pode ser apagado devido á existencia de Registo associados</li>
        </ul>
    <ul>
        <li id="kk" hidden="hidden">Impossivel eliminar este Motivo</li>
    </ul>
    }

</h3>
<div class="table-bordered">
    <h4>Motivo</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipoMotivo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoMotivo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NomeMotivo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomeMotivo)
        </dd>
    </dl>
    @if (Model.isDeletable) { 
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdMotivo" />
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        <a type="button" class="btn btn-info pull-right" asp-action="Index">Cancelar</a>
    </form>
    }
    
</div>

LesGrupo8Bioterio/Views/Motivoes/Details.cshtml
@model LesGrupo8Bioterio.Motivo
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="breadcrumb-item"><a asp-controller="CircuitoTanques" asp-action="Index">Circuito de Tanques</a></li>
        <li class="breadcrumb-item"><a asp-controller="Tanques" asp-action="Index">Tanques</a></li>
        <li class="breadcrumb-item"><a asp-controller="RegRemocoes" asp-action="Index">Registo de Remoções</a></li>
        <li class="breadcrumb-item"><a asp-controller="Motivoes" asp-action="Index">Motivos de Remoção</a></li>
        <li class="breadcrumb-item active" aria-current="page">Detalhes</li>
    </ol>
</nav>

<h2>Detalhes</h2>
<div>
    <h4>Motivo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipoMotivo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoMotivo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NomeMotivo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomeMotivo)
        </dd>
    </dl>
</div>
<div class="form-group">
    <a type="button" class="btn btn-info" asp-action="Edit" asp-route-id="@Model.IdMotivo">Editar</a>
    <a type="button" class="btn btn-danger pull-right" asp-action="Delete" asp-route-id="@Model.IdMotivo">Eliminar</a>
    <a type="button" class="btn btn-info" asp-action="Index">Voltar à lista</a>
</div>

LesGrupo8Bioterio/Views/Motivoes/Edit.cshtml
@model LesGrupo8Bioterio.Motivo
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="breadcrumb-item"><a asp-controller="CircuitoTanques" asp-action="Index">Circuito de Tanques</a></li>
        <li class="breadcrumb-item"><a asp-controller="Tanques" asp-action="Index">Tanques</a></li>
        <li class="breadcrumb-item"><a asp-controller="RegRemocoes" asp-action="Index">Registo de Remoções</a></li>
        <li class="breadcrumb-item"><a asp-controller="Motivoes" asp-action="Index">Motivos de Remoção</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar</li>
    </ol>
</nav>

<h2>Editar</h2>
<h4>Motivo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdMotivo" />
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Tipo de Motivo" data-content="Tipo de Motivo de Remoção de Individuos"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="TipoMotivo" class="control-label"></label>
                <input asp-for="TipoMotivo" class="form-control" />
                <span asp-validation-for="TipoMotivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Designação do Motivo" data-content="Designação do Motivo que leva à remoção de Individuos"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="NomeMotivo" class="control-label"></label>
                <input asp-for="NomeMotivo" class="form-control" />
                <span asp-validation-for="NomeMotivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Confirmar" class="btn btn-success" />
                <a type="button" class="btn btn-info" asp-action="Index">Cancelar</a>
            </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover();
    });</script>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LesGrupo8Bioterio/Views/Motivoes/Index.cshtml
@model IEnumerable<LesGrupo8Bioterio.Motivo>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
        <li class="breadcrumb-item"><a asp-controller="CircuitoTanques" asp-action="Index">Circuito de Tanques</a></li>
        <li class="breadcrumb-item"><a asp-controller="Tanques" asp-action="Index">Tanques</a></li>
        <li class="breadcrumb-item"><a asp-controller="RegRemocoes" asp-action="Index">Registo de Remoções</a></li>
        <li class="breadcrumb-item active" aria-current="page">Motivos de Remoção</li>
    </ol>
</nav>

<h2>Motivos de remoções</h2>
<p>
    <a type="button" class="btn btn-info" asp-action="Create">Adicionar motivo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TipoMotivo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomeMotivo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoMotivo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeMotivo)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdMotivo"><span class="glyphicon glyphicon-pencil"></span></a> |
                    <a asp-action="Details" asp-route-id="@item.IdMotivo"><span class="glyphicon glyphicon-eye-open"></span></a> |
                    <a asp-action="Delete" asp-route-id="@item.IdMotivo"><span class="glyphicon glyphicon-trash"></span></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div style="align-right">
    <a class="btn btn-info pull-right" asp-area="" asp-controller="RegRemocoes" asp-action="Index">Voltar aos registos de remoções</a>
</div>