LesGrupo8Bioterio/Controllers/ProjetoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LesGrupo8Bioterio;
using LesGrupo8Bioterio.Models;

namespace LesGrupo8Bioterio.Controllers
{
    public class ProjetoesController : Controller
    {
        private readonly bd_lesContext _context;

        public ProjetoesController(bd_lesContext context)
        {
            _context = context;
        }



        // GET: Projetoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Projeto.ToListAsync());
        }

        private Projeto SetRelations(Projeto projeto, int? id)
        {

            var ensaios = _context.Ensaio.Where(b => EF.Property<int>(b, "ProjetoIdProjeto") == id);
            var elementoequipa = _context.Elementoequipa.Where(b => EF.Property<int>(b, "ProjetoIdProjeto") == id);
            var circuitotanque = _context.CircuitoTanque.Where(b => EF.Property<int>(b, "ProjetoIdProjeto") == id);

            projeto.objetoEN = ensaios;
            projeto.CircuitoQuery = circuitotanque;
            projeto.objetoEE = elementoequipa;

            if (projeto.objetoEN.Any() || projeto.objetoEE.Any() || circuitotanque.Any())
            {
                projeto.deletable = false;
            }
            else
            {
                projeto.deletable = true;
            }
            return projeto;
        }

        // GET: Projetoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projeto = await _context.Projeto
                .SingleOrDefaultAsync(m => m.IdProjeto == id);
            
            var circuito =  _context.CircuitoTanque
                .Include(e => e.ProjetoIdProjetoNavigation).Where(m => m.ProjetoIdProjeto == id);

            var ensaio = _context.Ensaio.Include(e => e.LoteIdLoteNavigation).Where(m => m.ProjetoIdProjeto == id);

            var elementoequipa = _context.Elementoequipa.Where(m => m.ProjetoIdProjeto == id);
            if(elementoequipa != null)
            {
                projeto.objetoEE = elementoequipa;
            }
            if (ensaio != null)
            {
                projeto.objetoEN = ensaio;
            }
            if (circuito != null)
            {
                projeto.CircuitoQuery = circuito;
            }
            if (projeto == null)
            {
                return NotFound();
            }

            projeto.data = projeto.DataInicio.Day + "/" + projeto.DataInicio.Month + "/" + projeto.DataInicio.Year;
            projeto.data2 = projeto.DataFim.Day + "/" + projeto.DataFim.Month + "/" + projeto.DataFim.Year;
            if (projeto.SubmisInsEurop.Equals(true))
            {
                projeto.auto_Euro = "Sim";

            }
            else
            {
                projeto.auto_Euro = "Não";
            }

            return View(projeto);
        }

        // GET: Projetoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projetoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProjeto,Nome,DataInicio,DataFim,AutorizacaoDgva,RefOrbea,SubmisInsEurop,NroAnimaisAutoriz")] Projeto projeto)
        {
            if(projeto.DataFim < projeto.DataInicio)
            {
                ModelState.AddModelError("DataFim", "A Data de Fim é menor que a Data de Inicio");
                ModelState.AddModelError("DataInicio", "A Data de Fim é menor que a Data de Inicio");
            }
            if (ModelState.IsValid)
            {
                
                _context.Add(projeto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(projeto);
        }

        // GET: Projetoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projeto = await _context.Projeto.SingleOrDefaultAsync(m => m.IdProjeto == id);

            if (projeto == null || projeto.isarchived == 1)
            {
                return NotFound();
            }

            return View(projeto);
        }

        // POST: Projetoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProjeto,Nome,DataInicio,DataFim,AutorizacaoDgva,RefOrbea,SubmisInsEurop,NroAnimaisAutoriz")] Projeto projeto)
        {
            if (id != projeto.IdProjeto || projeto.isarchived == 1)
            {
                return NotFound();
            }
            if (projeto.DataFim < projeto.DataInicio)
            {
                ModelState.AddModelError("DataFim", "A Data de Fim é menor que a Data de Inicio");
                ModelState.AddModelError("DataInicio", "A Data de Fim é menor que a Data de Inicio");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projeto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjetoExists(projeto.IdProjeto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(projeto);
        }

        // GET: Projetoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projeto = await _context.Projeto
                .SingleOrDefaultAsync(m => m.IdProjeto == id);
            if (projeto == null || projeto.isarchived == 1)
            {
                return NotFound();
            }

            projeto = SetRelations(projeto, projeto.IdProjeto);
            projeto.data = projeto.DataInicio.Day + "/" + projeto.DataInicio.Month + "/" + projeto.DataInicio.Year;
            projeto.data2 = projeto.DataFim.Day + "/" + projeto.DataFim.Month + "/" + projeto.DataFim.Year;
            if (projeto.SubmisInsEurop.Equals(true))
            {
                projeto.auto_Euro = "Sim";

            }
            else
            {
                projeto.auto_Euro = "Não";
            }

            return View(projeto);
        }

        // POST: Projetoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projeto = await _context.Projeto.SingleOrDefaultAsync(m => m.IdProjeto == id);
            var ensaios = _context.Ensaio.Where(b => EF.Property<int>(b, "ProjetoIdProjeto") == id);
            var elementoequipa = _context.Elementoequipa.Where(b => EF.Property<int>(b, "ProjetoIdProjeto") == id);
            var circuitotanque = _context.CircuitoTanque.Where(b => EF.Property<int>(b, "ProjetoIdProjeto") == id);

            
            foreach (var ensaio in ensaios)
            {
                ensaio.isarchived = 1;
                _context.Ensaio.Update(ensaio);
            }
            foreach(var elementos in elementoequipa)
            {
                elementos.isarchived = 1;
                _context.Elementoequipa.Update(elementos);
            }
            foreach (var circuito in circuitotanque)
            {
                var tanques = _context.Tanque.Where(b => EF.Property<int>(b, "CircuitoTanqueIdCircuito") == circuito.IdCircuito);
                var regCondAmb = _context.RegCondAmb.Where(b => EF.Property<int>(b, "CircuitoTanqueIdCircuito") == id);

                foreach (var tanque in tanques) { 
                var regRemocoes = _context.RegRemocoes.Where(b => EF.Property<int>(b, "TanqueIdTanque") == tanque.IdTanque);
                var regAmostragens = _context.RegAmostragens.Where(b => EF.Property<int>(b, "TanqueIdTanque") == tanque.IdTanque);
                var regManu = _context.RegManutencao.Where(b => EF.Property<int>(b, "TanqueIdTanque") == tanque.IdTanque);
                var regTrat = _context.RegTratamento.Where(b => EF.Property<int>(b, "TanqueIdTanque") == tanque.IdTanque);
                var regAli = _context.RegAlimentar.Where(b => EF.Property<int>(b, "TanqueIdTanque") == tanque.IdTanque);

                    foreach (var regRemocao in regRemocoes)
                    {
                        regRemocao.isarchived = 1;
                        _context.RegRemocoes.Update(regRemocao);
                    }
                    foreach (var regAmostragem in regAmostragens)
                    {
                        regAmostragem.isarchived = 1;
                        _context.RegAmostragens.Update(regAmostragem);
                    }
                    foreach (var regManutencao in regManu)
                    {
                        regManutencao.isarchived = 1;
                        _context.RegManutencao.Update(regManutencao);
                    }
                    foreach (var regTratamento in regTrat)
                    {
                        regTratamento.isarchived = 1;

LesGrupo8Bioterio/Views/Projetoes/Create.cshtml
@model LesGrupo8Bioterio.Projeto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
              <li class="breadcrumb-item active" aria-current="page">Criar</li>
    </ol>
</nav>
<h2>Criar</h2>

<h4>Projeto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Nome do Projeto" data-content="Nome do Projeto ou Referência FCT"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" required />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Data de Inicio" data-content="Data apartir da qual o Projeto se irá Inicializar"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="DataInicio" class="control-label"></label>
                <input type="date" asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Data de Fim" data-content="Data de término planeado para o Projeto"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="DataFim" class="control-label"></label>
                <input type="date" asp-for="DataFim" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Autorização DGVA" data-content="Código da Autorização DGVA para o Projeto"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="AutorizacaoDgva" class="control-label"></label>
                <input asp-for="AutorizacaoDgva" class="form-control" required />
                <span asp-validation-for="AutorizacaoDgva" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Referência ORBEA" data-content="Referência ORBEA do Projeto"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="RefOrbea" class="control-label"></label>
                <input asp-for="RefOrbea" class="form-control" required />
                <span asp-validation-for="RefOrbea" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Instãncias Europeias" data-content="Submissão a Instâncias Europeias"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="SubmisInsEurop" class="control-label"></label>
                <select required class="form-control" type="text" id="SubmisInsEurop" name="SubmisInsEurop">
                    <option value="">Escolha uma opção</option>
                    <option value="True">Sim</option>
                    <option value="False">Não</option>
                </select>
                <span asp-validation-for="SubmisInsEurop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Animais autorizados" data-content="Número de animais autorizados para o Projeto"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="NroAnimaisAutoriz" class="control-label"></label>
                <input asp-for="NroAnimaisAutoriz" class="form-control" required />
                <span asp-validation-for="NroAnimaisAutoriz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Confirmar" class="btn btn-success" />
                <a class="btn btn-info" asp-action="Index">Cancelar</a>
            </div>
        </form>
    </div>
</div>

<script>$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
    });</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LesGrupo8Bioterio/Views/Projetoes/Delete.cshtml
@model LesGrupo8Bioterio.Projeto

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Arquivar</li>
    </ol>
</nav>
<h2>Arquivar</h2>

<h3 class="alert alert-danger">
    <ul>
        <li> Tem a certeza que pretende Arquivar este Projeto?</li>
        <li>Ao Arquivar este Projeto estará a Arquivar todos os Ensaios assim como todos os Circuitos associados ao mesmo!</li>
        <li>Estará ainda a Arquivar tambem os Registos de elementos que tenham trabalhado neste projeto!</li>
        <li>Após arquivada toda a informação passará a ser inalterável</li>
    </ul>
</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DataInicio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.data2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AutorizacaoDgva)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AutorizacaoDgva)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RefOrbea)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RefOrbea)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubmisInsEurop)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.auto_Euro)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NroAnimaisAutoriz)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NroAnimaisAutoriz)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdProjeto" />
        <input type="submit" value="Arquivar" class="btn btn-danger" /> 
        <a type="button" class="btn btn-primary" asp-action="Index">Cancelar</a>
    </form>
</div>

LesGrupo8Bioterio/Views/Projetoes/Details.cshtml
@model LesGrupo8Bioterio.Projeto
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
              <li class="breadcrumb-item active" aria-current="page">Detalhes</li>
    </ol>
</nav>
@if (Model.isarchived == 1)
{
    <h3 class="alert alert-danger">
        <ul>
            <li> Este Projeto encontra-se <b>Arquivado</b> </li>
        </ul>
    </h3>
}
<div class="col-lg-12">
    <h4>Projeto</h4>
    <hr />
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DataInicio)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.data)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DataFim)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.data2)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AutorizacaoDgva)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AutorizacaoDgva)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.RefOrbea)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.RefOrbea)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.SubmisInsEurop)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.auto_Euro)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.NroAnimaisAutoriz)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.NroAnimaisAutoriz)
            </dd>
        </dl>

    </div>

    <div class="col-md-6">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#ensaios" id="ensaios_tab">Ensaios</a></li>
            <li><a data-toggle="tab" href="#membros" id="membros_tab">Membros</a></li>
            <li><a data-toggle="tab" href="#Circuitos" id="circuito_tab">Circuito</a></li>
        </ul>
        <div class="tab-content">
            <div id="ensaios" class="tab-pane fade in active">
                @* <a type="button" class="btn btn-success" asp-controller="Ensaios" asp-action="Create" asp-route-id="@Model.IdProjeto">Registar Ensaio </a>*@
                @if (Model.objetoEN != null)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @* @Html.DisplayNameFor(model => model.dummyEnsaio.LoteIdLoteNavigation)*@Lote
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.dummyEnsaio.NroAnimaisAutoriz)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.dummyEnsaio.DataInicio)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.dummyEnsaio.DataFim)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.dummyEnsaio.DescTratamento)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.dummyEnsaio.GrauSeveridade)
                                </th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.objetoEN)
                            {
                                item.data = item.DataInicio.Day + "/" + item.DataInicio.Month + "/" + item.DataInicio.Year;
                                item.data2 = item.DataFim.Day + "/" + item.DataFim.Month + "/" + item.DataFim.Year;
                            <tr>
                                <td>
                                    @Html.DisplayFor(modell => item.LoteIdLoteNavigation.CodigoLote)
                                </td>
                                <td>
                                    @Html.DisplayFor(modell => item.NroAnimaisAutoriz)
                                </td>
                                <td>
                                    @Html.DisplayFor(modell => item.data)
                                </td>
                                <td>
                                    @Html.DisplayFor(modell => item.data2)
                                </td>
                                <td>
                                    @Html.DisplayFor(modell => item.DescTratamento)
                                </td>
                                <td>
                                    @Html.DisplayFor(modell => item.GrauSeveridade)
                                </td>

                            </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
            <div id="membros" class="tab-pane fade">
                @if (Model.objetoEE != null)
                {

                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.dummyEE.Nome)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.dummyEE.Função)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.objetoEE)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(model => item.Nome)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Função)
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
            <div id="Circuitos" class="tab-pane fade">
               
                @if (Model.CircuitoQuery != null)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    Codigo Circuito
                                </th>
                            </tr>
                           
                        </thead>
                        <tbody>
                            @foreach (var item in Model.CircuitoQuery)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(model => item.CodigoCircuito)
                                        @*<a asp-controller="CircuitoTanques" asp-action="Details" asp-route-id="@Model.CircuitoQuery.IdCircuito"><span class="glyphicon glyphicon-eye-open"></span></a>*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <h4>Nenhum Circuito Associado</h4>
                }
            </div>
        </div>
    </div>

</div>
<div>
    @if (Model.isarchived == 0)
    {
    <a type="button" class="btn btn-success" asp-action="Edit" asp-route-id="@Model.IdProjeto">Editar</a>}
    <a type="button" class="btn btn-primary" asp-action="Index">Retornar</a>
    @if(Model.isarchived == 0){
    <a type="button" class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.IdProjeto">Arquivar Projeto</a>}
</div>
</div>

LesGrupo8Bioterio/Views/Projetoes/Edit.cshtml
@model LesGrupo8Bioterio.Projeto
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Página Inicial</a></li>
        <li class="breadcrumb-item"><a asp-controller="Projetoes" asp-action="Index">Projetos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar</li>
    </ol>
</nav>
<h2>Editar</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdProjeto" />
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Nome do Projeto" data-content="Nome do Projeto ou Referência FCT"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Data de Inicio" data-content="Data apartir da qual o Projeto se irá Inicializar"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="DataInicio" class="control-label"></label>
                <input type="date" asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Data de Fim" data-content="Data de término planeado para o Projeto"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="DataFim" class="control-label"></label>
                <input type="date" asp-for="DataFim" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Autorização DGVA" data-content="Código da Autorização DGVA para o Projeto"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="AutorizacaoDgva" class="control-label"></label>
                <input asp-for="AutorizacaoDgva" class="form-control" required />
                <span asp-validation-for="AutorizacaoDgva" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Referência ORBEA" data-content="Referência ORBEA do Projeto"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="RefOrbea" class="control-label"></label>
                <input asp-for="RefOrbea" class="form-control" required />
                <span asp-validation-for="RefOrbea" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Instãncias Europeias" data-content="Submissão a Instâncias Europeias"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="SubmisInsEurop" class="control-label"></label>
                <select required class="form-control" type="text" id="SubmisInsEurop" name="SubmisInsEurop">
                    <option value="">Escolha uma opção</option>
                    <option value="True">Sim</option>
                    <option value="False">Não</option>
                </select>
                <span asp-validation-for="SubmisInsEurop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a href="#" data-toggle="popover" title="Animais autorizados" data-content="Número de animais autorizados para o Projeto"><span class="glyphicon glyphicon-question-sign"></span></a>
                <label asp-for="NroAnimaisAutoriz" class="control-label"></label>
                <input asp-for="NroAnimaisAutoriz" class="form-control" required />
                <span asp-validation-for="NroAnimaisAutoriz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<div>
    <a type="button" class="btn btn-primary" asp-action="Index">Retornar</a>
</div>
<script>
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover();
    });
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}